# Generated by Django 5.2.16 on 2026-07-09 19:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkedInProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("linkedin_url", models.URLField(db_index=True, unique=True)),
                ("linkedin_id", models.CharField(blank=True, max_length=200)),
                ("linkedin_num_id", models.CharField(blank=True, max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("headline", models.CharField(blank=True, max_length=500)),
                ("summary", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=5)),
                ("avatar", models.URLField(blank=True)),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("connections", models.IntegerField(blank=True, null=True)),
                ("current_company_name", models.CharField(blank=True, max_length=255)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "linkedin_profiles",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["linkedin_url"], name="linkedin_pr_linkedi_db4371_idx"
                    ),
                    models.Index(
                        fields=["linkedin_id"], name="linkedin_pr_linkedi_15fbd2_idx"
                    ),
                    models.Index(
                        fields=["last_synced"], name="linkedin_pr_last_sy_62719f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("end_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description_HTML", models.TextField(blank=True, default="")),
                ("company_logo_url", models.URLField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_experiences",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["profile"], name="linkedin_ex_profile_6d7503_idx"
                    ),
                    models.Index(
                        fields=["company"], name="linkedin_ex_company_3f1644_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("end_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("school", models.CharField(db_index=True, max_length=255)),
                (
                    "degree_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("grade", models.CharField(blank=True, default="", max_length=100)),
                ("activities_and_societies", models.TextField(blank=True, default="")),
                ("school_linkedin_url", models.URLField(blank=True, default="")),
                ("school_facebook_url", models.URLField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, default="")),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_educations",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["profile"], name="linkedin_ed_profile_82b457_idx"
                    ),
                    models.Index(
                        fields=["school"], name="linkedin_ed_school_6baf82_idx"
                    ),
                    models.Index(
                        fields=["start_year"], name="linkedin_ed_start_y_cebbd8_idx"
                    ),
                    models.Index(
                        fields=["end_year"], name="linkedin_ed_end_yea_40aea5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("end_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("authority", models.CharField(blank=True, max_length=255)),
                ("license_number", models.CharField(blank=True, max_length=255)),
                ("display_source", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_certifications",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["profile"], name="linkedin_ce_profile_e11e22_idx"
                    ),
                    models.Index(
                        fields=["authority"], name="linkedin_ce_authori_a7bd66_idx"
                    ),
                    models.Index(fields=["name"], name="linkedin_ce_name_f5e588_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("end_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("project_url", models.URLField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_projects",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["profile"], name="linkedin_pr_profile_b47101_idx"
                    ),
                    models.Index(fields=["title"], name="linkedin_pr_title_efde24_idx"),
                    models.Index(
                        fields=["start_year"], name="linkedin_pr_start_y_467cc2_idx"
                    ),
                ],
            },
        ),
    ]
