# Generated by Django 5.2.16 on 2026-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinprofile",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="linkedinprofile",
            name="linkedin_num_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
