# Generated by Django 5.2.16 on 2026-07-13 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("linkedin", "0002_alter_linkedinprofile_linkedin_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_description", models.TextField()),
                ("overall_score", models.PositiveSmallIntegerField()),
                ("experience_score", models.PositiveSmallIntegerField()),
                ("projects_score", models.PositiveSmallIntegerField()),
                ("skills_score", models.PositiveSmallIntegerField()),
                ("summary_score", models.PositiveSmallIntegerField()),
                ("suggestions", models.JSONField(default=list)),
                ("llm_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="analysis_an_created_079746_idx"
                    ),
                    models.Index(
                        fields=["profile"], name="analysis_an_profile_e72a68_idx"
                    ),
                ],
            },
        ),
    ]
