# Generated by Django 5.2.16 on 2026-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="missing_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="analysis",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
